// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.20;

import "../../interfaces/ITickets404.sol";

interface IMockedTickets404 is ITickets404 {
    function setPeriod(uint256 period) external;
    function setTicketSeed(uint256 rawSeed, uint256 tokenId, bool newHasRef) external;
    function getTicketSeed(uint256 tokenId) external view returns (uint256 s, uint256 t, bool r);
    function isTicketPending(uint256 tokenId) external view returns (bool);
    function isTicketFailed(uint256 tokenId) external view returns (bool);
    function requestForTokenId(uint256 tokenId) external view returns (bytes32);
}